language: java
script: mvn clean package
jdk:
  - oraclejdk8
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database test;' -U postgres
deploy:
  provider: heroku
  api_key: "0e090e2e-f03f-4ced-a4f8-7ef4724173b0"
  app: amt-dev
